module.exports = {
  content: ["./src/**/*.{html,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      animation: {
        marquee: "marquee 20s linear infinite",
        marquee2: "marquee2 20s linear infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-100%)" },
        },
        marquee2: {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0%)" },
        },
      },
      screens: {
        xs: "480px",
        smlmax: {max: "767px"},
        mdx: "992px",
        mdlmax: { max: "992px" },
      },
      fontFamily: {
        FGMR: ["Franklin Gothic Medium Regular", "Arial"],
        FGBI: ["Franklin Gothic Book Italic", "Arial"],
        FGMI: ["Franklin Gothic Medium Italic", "Arial"],
        FGBR: ["Franklin Gothic Book Regular", "Arial"],
        Arial: ["Arial"],
      },
      fontSize: {
        "heading-one-xl": "55px",
        "heading-one": "32px",
        "heading-two": "25px",
        "heading-three": "20px",
        "heading-four": "18px",
        "heading-five": "16px",
        "heading-six": "14px",
        xxs: "10px",
        xs: "12px",
        sm: "14px",
        md: "16px",
        lg: "18px",
        xl: "20px",
        "36px": "36px",
        "60px": "60px",
      },
      colors: {
        transparent: "transparent",
        current: "currentColor",
        white: "#ffffff",
        black: "#000000",
        "black-base": "#242424",
        "dark-blue": "#004992",
        "light-blue": "#29A9E0",
        orange: "#F26F23",
        "orange-hover": "#F25F09",
        green: "#55B047",
        silver: "#929497",
        gray: "#808080",
        "gray-dark": "#888888",
        "gray-dark-alt": "#969696",
        "gray-light": "#F4F4F4",
        "gray-light-alt": "#FAFAFA",
        "gray-border": "#DDDDDD",
        red: "#E32332",
        light2: "#d8d8d8",
        "custom-black": "#272727",
      },
      height: {
        "15px": "15px",
        "20px": "20px",
        "25px": "25px",
        "40px": "40px",
        "835px": "825px",
      },
      minHeight: {
        "100vh": "calc(100vh - 100px)",
      },
      width: {
        "120px": "120px",
        "400px": "400px",
      },
      maxWidth: {
        "400px": "400px",
      },
      margin: {
        "5px": "5px",
        "10px": "10px",
        "15px": "15px",
        "20px": "20px",
        "30px": "30px",
        "40px": "40px",
        "45px": "45px",
        "60px": "60px",
        "90px": "90px",
        "100px": "100px",
      },
      padding: {
        "5px": "5px",
        "10px": "10px",
        "15px": "15px",
        "20px": "20px",
        "30px": "30px",
        "45px": "45px",
        "60px": "60px",
        "90px": "90px",
      },
      borderWidth: {
        1: "1px",
      },
      borderColor: {
        "custom-gray": "#D8D8D8",
      },
      listStyleType: {
        plus: '"+ "',
      },
      backgroundImage: {
        "program-design": "url('src/static/images/image-program-design.jpg')",
      },
      spacing: {
        "450px": "450px",
      },
    },
  },
  plugins: [],
};
